-- +goose Up
SET ROLE app_owner;

CREATE SCHEMA IF NOT EXISTS storm;

REVOKE ALL ON SCHEMA storm FROM PUBLIC;
GRANT USAGE ON SCHEMA storm TO app_user;

-- Revoke privileges for future schemas, tables and sequences for PUBLIC
ALTER DEFAULT PRIVILEGES FOR ROLE app_owner IN SCHEMA storm
    REVOKE ALL ON TABLES FROM PUBLIC;

ALTER DEFAULT PRIVILEGES FOR ROLE app_owner IN SCHEMA storm
    REVOKE ALL ON SEQUENCES FROM PUBLIC;

ALTER DEFAULT PRIVILEGES FOR ROLE app_owner IN SCHEMA storm
    REVOKE ALL ON FUNCTIONS FROM PUBLIC;

RESET ROLE;
-- +goose Down