-- +goose Up
SET ROLE app_owner;

CREATE SCHEMA IF NOT EXISTS pet_guides;

REVOKE ALL ON SCHEMA pet_guides FROM PUBLIC;
GRANT USAGE ON SCHEMA pet_guides TO app_user;

-- Revoke privileges for future schemas, tables and sequences for PUBLIC
ALTER DEFAULT PRIVILEGES FOR ROLE app_owner IN SCHEMA pet_guides
    REVOKE ALL ON TABLES FROM PUBLIC;

ALTER DEFAULT PRIVILEGES FOR ROLE app_owner IN SCHEMA pet_guides
    REVOKE ALL ON SEQUENCES FROM PUBLIC;

ALTER DEFAULT PRIVILEGES FOR ROLE app_owner IN SCHEMA pet_guides
    REVOKE ALL ON FUNCTIONS FROM PUBLIC;

RESET ROLE;
-- +goose Down